include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    flutter_style_todos: ignore
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
    one_member_abstracts: ignore
    prefer_int_literals: ignore
    unnecessary_underscores: ignore
    discarded_futures: ignore
    comment_references: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    sort_pub_dependencies: false
